// Code generated by internal/cmd/gen_incb; DO NOT EDIT.

package uniseg

// incb are token from
// https://www.unicode.org/Public/15.1.0/ucd/DerivedCoreProperties.txt
// See https://www.unicode.org/license.html for the Unicode license agreement.
var incb = dictionary[incbProperty]{
	{runeRange{0xA8E0, 0xA8F1}, incbExtend},    // Mn  [18] COMBINING DEVANAGARI DIGIT ZERO..COMBINING DEVANAGARI SIGN AVAGRAHA
	{runeRange{0x0C4D, 0x0C4D}, incbLinker},    // Mn       TELUGU SIGN VIRAMA
	{runeRange{0x1183A, 0x1183A}, incbExtend},  // Mn       DOGRA SIGN NUKTA
	{runeRange{0x0958, 0x095F}, incbConsonant}, // Lo   [8] DEVANAGARI LETTER QA..DEVANAGARI LETTER YYA
	{runeRange{0x1A60, 0x1A60}, incbExtend},    // Mn       TAI THAM SIGN SAKOT
	{runeRange{0x110BA, 0x110BA}, incbExtend},  // Mn       KAITHI SIGN NUKTA
	{runeRange{0x1D17B, 0x1D182}, incbExtend},  // Mn   [8] MUSICAL SYMBOL COMBINING ACCENT..MUSICAL SYMBOL COMBINING LOURE
	{runeRange{0x0711, 0x0711}, incbExtend},    // Mn       SYRIAC LETTER SUPERSCRIPT ALAPH
	{runeRange{0x0AB5, 0x0AB9}, incbConsonant}, // Lo   [5] GUJARATI LETTER VA..GUJARATI LETTER HA
	{runeRange{0x0F74, 0x0F74}, incbExtend},    // Mn       TIBETAN VOWEL SIGN U
	{runeRange{0x1DC0, 0x1DFF}, incbExtend},    // Mn  [64] COMBINING DOTTED GRAVE ACCENT..COMBINING RIGHT ARROWHEAD AND DOWN ARROWHEAD BELOW
	{runeRange{0x10A0F, 0x10A0F}, incbExtend},  // Mn       KHAROSHTHI SIGN VISARGA
	{runeRange{0x11366, 0x1136C}, incbExtend},  // Mn   [7] COMBINING GRANTHA DIGIT ZERO..COMBINING GRANTHA DIGIT SIX
	{runeRange{0x11D97, 0x11D97}, incbExtend},  // Mn       GUNJALA GONDI VIRAMA
	{runeRange{0x1E026, 0x1E02A}, incbExtend},  // Mn   [5] COMBINING GLAGOLITIC LETTER YO..COMBINING GLAGOLITIC LETTER FITA
	{runeRange{0x05C7, 0x05C7}, incbExtend},    // Mn       HEBREW POINT QAMATS QATAN
	{runeRange{0x0859, 0x085B}, incbExtend},    // Mn   [3] MANDAIC AFFRICATION MARK..MANDAIC GEMINATION MARK
	{runeRange{0x09DC, 0x09DD}, incbConsonant}, // Lo   [2] BENGALI LETTER RRA..BENGALI LETTER RHA
	{runeRange{0x0B3C, 0x0B3C}, incbExtend},    // Mn       ORIYA SIGN NUKTA
	{runeRange{0x0E48, 0x0E4B}, incbExtend},    // Mn   [4] THAI CHARACTER MAI EK..THAI CHARACTER MAI CHATTAWA
	{runeRange{0x108D, 0x108D}, incbExtend},    // Mn       MYANMAR SIGN SHAN COUNCIL EMPHATIC TONE
	{runeRange{0x1BE6, 0x1BE6}, incbExtend},    // Mn       BATAK SIGN TOMPI
	{runeRange{0x302A, 0x302D}, incbExtend},    // Mn   [4] IDEOGRAPHIC LEVEL TONE MARK..IDEOGRAPHIC ENTERING TONE MARK
	{runeRange{0xAAF6, 0xAAF6}, incbExtend},    // Mn       MEETEI MAYEK VIRAMA
	{runeRange{0x10F46, 0x10F50}, incbExtend},  // Mn  [11] SOGDIAN COMBINING DOT BELOW..SOGDIAN COMBINING STROKE BELOW
	{runeRange{0x111CA, 0x111CA}, incbExtend},  // Mn       SHARADA SIGN NUKTA
	{runeRange{0x114C3, 0x114C3}, incbExtend},  // Mn       TIRHUTA SIGN NUKTA
	{runeRange{0x11A47, 0x11A47}, incbExtend},  // Mn       ZANABAZAR SQUARE SUBJOINER
	{runeRange{0x1BC9E, 0x1BC9E}, incbExtend},  // Mn       DUPLOYAN DOUBLE MARK
	{runeRange{0x1E000, 0x1E006}, incbExtend},  // Mn   [7] COMBINING GLAGOLITIC LETTER AZU..COMBINING GLAGOLITIC LETTER ZHIVETE
	{runeRange{0x1E2EC, 0x1E2EF}, incbExtend},  // Mn   [4] WANCHO TONE TUP..WANCHO TONE KOINI
	{runeRange{0x0591, 0x05BD}, incbExtend},    // Mn  [45] HEBREW ACCENT ETNAHTA..HEBREW POINT METEG
	{runeRange{0x06D6, 0x06DC}, incbExtend},    // Mn   [7] ARABIC SMALL HIGH LIGATURE SAD WITH LAM WITH ALEF MAKSURA..ARABIC SMALL HIGH SEEN
	{runeRange{0x0816, 0x0819}, incbExtend},    // Mn   [4] SAMARITAN MARK IN..SAMARITAN MARK DAGESH
	{runeRange{0x0915, 0x0939}, incbConsonant}, // Lo  [37] DEVANAGARI LETTER KA..DEVANAGARI LETTER HA
	{runeRange{0x09B2, 0x09B2}, incbConsonant}, // Lo       BENGALI LETTER LA
	{runeRange{0x0A3C, 0x0A3C}, incbExtend},    // Mn       GURMUKHI SIGN NUKTA
	{runeRange{0x0B15, 0x0B28}, incbConsonant}, // Lo  [20] ORIYA LETTER KA..ORIYA LETTER NA
	{runeRange{0x0B71, 0x0B71}, incbConsonant}, // Lo       ORIYA LETTER WA
	{runeRange{0x0D15, 0x0D3A}, incbConsonant}, // Lo  [38] MALAYALAM LETTER KA..MALAYALAM LETTER TTTA
	{runeRange{0x0F35, 0x0F35}, incbExtend},    // Mn       TIBETAN MARK NGAS BZUNG NYI ZLA
	{runeRange{0x0F86, 0x0F87}, incbExtend},    // Mn   [2] TIBETAN SIGN LCI RTAGS..TIBETAN SIGN YANG RTAGS
	{runeRange{0x17DD, 0x17DD}, incbExtend},    // Mn       KHMER SIGN ATTHACAN
	{runeRange{0x1ABF, 0x1ACE}, incbExtend},    // Mn  [16] COMBINING LATIN SMALL LETTER W BELOW..COMBINING LATIN SMALL LETTER INSULAR T
	{runeRange{0x1CE2, 0x1CE8}, incbExtend},    // Mn   [7] VEDIC SIGN VISARGA SVARITA..VEDIC SIGN VISARGA ANUDATTA WITH TAIL
	{runeRange{0x20E5, 0x20F0}, incbExtend},    // Mn  [12] COMBINING REVERSE SOLIDUS OVERLAY..COMBINING ASTERISK ABOVE
	{runeRange{0xA674, 0xA67D}, incbExtend},    // Mn  [10] COMBINING CYRILLIC LETTER UKRAINIAN IE..COMBINING CYRILLIC PAYEROK
	{runeRange{0xAAB2, 0xAAB4}, incbExtend},    // Mn   [3] TAI VIET VOWEL I..TAI VIET VOWEL U
	{runeRange{0x101FD, 0x101FD}, incbExtend},  // Mn       PHAISTOS DISC SIGN COMBINING OBLIQUE STROKE
	{runeRange{0x10D24, 0x10D27}, incbExtend},  // Mn   [4] HANIFI ROHINGYA SIGN HARBAHAY..HANIFI ROHINGYA SIGN TASSI
	{runeRange{0x11070, 0x11070}, incbExtend},  // Mn       BRAHMI SIGN OLD TAMIL VIRAMA
	{runeRange{0x11133, 0x11134}, incbExtend},  // Mn   [2] CHAKMA VIRAMA..CHAKMA MAAYYAA
	{runeRange{0x112E9, 0x112EA}, incbExtend},  // Mn   [2] KHUDAWADI SIGN NUKTA..KHUDAWADI SIGN VIRAMA
	{runeRange{0x11446, 0x11446}, incbExtend},  // Mn       NEWA SIGN NUKTA
	{runeRange{0x116B7, 0x116B7}, incbExtend},  // Mn       TAKRI SIGN NUKTA
	{runeRange{0x11943, 0x11943}, incbExtend},  // Mn       DIVES AKURU SIGN NUKTA
	{runeRange{0x11D42, 0x11D42}, incbExtend},  // Mn       MASARAM GONDI SIGN NUKTA
	{runeRange{0x16AF0, 0x16AF4}, incbExtend},  // Mn   [5] BASSA VAH COMBINING HIGH TONE..BASSA VAH COMBINING HIGH-LOW TONE
	{runeRange{0x1D167, 0x1D169}, incbExtend},  // Mn   [3] MUSICAL SYMBOL COMBINING TREMOLO-1..MUSICAL SYMBOL COMBINING TREMOLO-3
	{runeRange{0x1D1AA, 0x1D1AD}, incbExtend},  // Mn   [4] MUSICAL SYMBOL COMBINING DOWN BOW..MUSICAL SYMBOL COMBINING SNAP PIZZICATO
	{runeRange{0x1E01B, 0x1E021}, incbExtend},  // Mn   [7] COMBINING GLAGOLITIC LETTER SHTA..COMBINING GLAGOLITIC LETTER YATI
	{runeRange{0x1E130, 0x1E136}, incbExtend},  // Mn   [7] NYIAKENG PUACHUE HMONG TONE-B..NYIAKENG PUACHUE HMONG TONE-D
	{runeRange{0x1E8D0, 0x1E8D6}, incbExtend},  // Mn   [7] MENDE KIKAKUI COMBINING NUMBER TEENS..MENDE KIKAKUI COMBINING NUMBER MILLIONS
	{runeRange{0x0350, 0x036F}, incbExtend},    // Mn  [32] COMBINING RIGHT ARROWHEAD ABOVE..COMBINING LATIN SMALL LETTER X
	{runeRange{0x05C1, 0x05C2}, incbExtend},    // Mn   [2] HEBREW POINT SHIN DOT..HEBREW POINT SIN DOT
	{runeRange{0x064B, 0x065F}, incbExtend},    // Mn  [21] ARABIC FATHATAN..ARABIC WAVY HAMZA BELOW
	{runeRange{0x06E7, 0x06E8}, incbExtend},    // Mn   [2] ARABIC SMALL HIGH YEH..ARABIC SMALL HIGH NOON
	{runeRange{0x07EB, 0x07F3}, incbExtend},    // Mn   [9] NKO COMBINING SHORT HIGH TONE..NKO COMBINING DOUBLE DOT ABOVE
	{runeRange{0x0825, 0x0827}, incbExtend},    // Mn   [3] SAMARITAN VOWEL SIGN SHORT A..SAMARITAN VOWEL SIGN U
	{runeRange{0x08CA, 0x08E1}, incbExtend},    // Mn  [24] ARABIC SMALL HIGH FARSI YEH..ARABIC SMALL HIGH SIGN SAFHA
	{runeRange{0x094D, 0x094D}, incbLinker},    // Mn       DEVANAGARI SIGN VIRAMA
	{runeRange{0x0995, 0x09A8}, incbConsonant}, // Lo  [20] BENGALI LETTER KA..BENGALI LETTER NA
	{runeRange{0x09BC, 0x09BC}, incbExtend},    // Mn       BENGALI SIGN NUKTA
	{runeRange{0x09F0, 0x09F1}, incbConsonant}, // Lo   [2] BENGALI LETTER RA WITH MIDDLE DIAGONAL..BENGALI LETTER RA WITH LOWER DIAGONAL
	{runeRange{0x0AAA, 0x0AB0}, incbConsonant}, // Lo   [7] GUJARATI LETTER PA..GUJARATI LETTER RA
	{runeRange{0x0ACD, 0x0ACD}, incbLinker},    // Mn       GUJARATI SIGN VIRAMA
	{runeRange{0x0B32, 0x0B33}, incbConsonant}, // Lo   [2] ORIYA LETTER LA..ORIYA LETTER LLA
	{runeRange{0x0B5C, 0x0B5D}, incbConsonant}, // Lo   [2] ORIYA LETTER RRA..ORIYA LETTER RHA
	{runeRange{0x0C2A, 0x0C39}, incbConsonant}, // Lo  [16] TELUGU LETTER PA..TELUGU LETTER HA
	{runeRange{0x0C58, 0x0C5A}, incbConsonant}, // Lo   [3] TELUGU LETTER TSA..TELUGU LETTER RRRA
	{runeRange{0x0D4D, 0x0D4D}, incbLinker},    // Mn       MALAYALAM SIGN VIRAMA
	{runeRange{0x0EC8, 0x0ECB}, incbExtend},    // Mn   [4] LAO TONE MAI EK..LAO TONE MAI CATAWA
	{runeRange{0x0F39, 0x0F39}, incbExtend},    // Mn       TIBETAN MARK TSA -PHRU
	{runeRange{0x0F80, 0x0F80}, incbExtend},    // Mn       TIBETAN VOWEL SIGN REVERSED I
	{runeRange{0x1037, 0x1037}, incbExtend},    // Mn       MYANMAR SIGN DOT BELOW
	{runeRange{0x1714, 0x1714}, incbExtend},    // Mn       TAGALOG SIGN VIRAMA
	{runeRange{0x1939, 0x193B}, incbExtend},    // Mn   [3] LIMBU SIGN MUKPHRENG..LIMBU SIGN SA-I
	{runeRange{0x1A7F, 0x1A7F}, incbExtend},    // Mn       TAI THAM COMBINING CRYPTOGRAMMIC DOT
	{runeRange{0x1B6B, 0x1B73}, incbExtend},    // Mn   [9] BALINESE MUSICAL SYMBOL COMBINING TEGEH..BALINESE MUSICAL SYMBOL COMBINING GONG
	{runeRange{0x1CD0, 0x1CD2}, incbExtend},    // Mn   [3] VEDIC TONE KARSHANA..VEDIC TONE PRENKHA
	{runeRange{0x1CF4, 0x1CF4}, incbExtend},    // Mn       VEDIC TONE CANDRA ABOVE
	{runeRange{0x20D0, 0x20DC}, incbExtend},    // Mn  [13] COMBINING LEFT HARPOON ABOVE..COMBINING FOUR DOTS ABOVE
	{runeRange{0x2D7F, 0x2D7F}, incbExtend},    // Mn       TIFINAGH CONSONANT JOINER
	{runeRange{0x3099, 0x309A}, incbExtend},    // Mn   [2] COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK..COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
	{runeRange{0xA6F0, 0xA6F1}, incbExtend},    // Mn   [2] BAMUM COMBINING MARK KOQNDON..BAMUM COMBINING MARK TUKWENTIS
	{runeRange{0xA9B3, 0xA9B3}, incbExtend},    // Mn       JAVANESE SIGN CECAK TELU
	{runeRange{0xAABE, 0xAABF}, incbExtend},    // Mn   [2] TAI VIET VOWEL AM..TAI VIET TONE MAI EK
	{runeRange{0xFB1E, 0xFB1E}, incbExtend},    // Mn       HEBREW POINT JUDEO-SPANISH VARIKA
	{runeRange{0x10376, 0x1037A}, incbExtend},  // Mn   [5] COMBINING OLD PERMIC LETTER AN..COMBINING OLD PERMIC LETTER SII
	{runeRange{0x10A3F, 0x10A3F}, incbExtend},  // Mn       KHAROSHTHI VIRAMA
	{runeRange{0x10EFD, 0x10EFF}, incbExtend},  // Mn   [3] ARABIC SMALL LOW WORD SAKTA..ARABIC SMALL LOW WORD MADDA
	{runeRange{0x10F82, 0x10F85}, incbExtend},  // Mn   [4] OLD UYGHUR COMBINING DOT ABOVE..OLD UYGHUR COMBINING TWO DOTS BELOW
	{runeRange{0x1107F, 0x1107F}, incbExtend},  // Mn       BRAHMI NUMBER JOINER
	{runeRange{0x11100, 0x11102}, incbExtend},  // Mn   [3] CHAKMA SIGN CANDRABINDU..CHAKMA SIGN VISARGA
	{runeRange{0x11173, 0x11173}, incbExtend},  // Mn       MAHAJANI SIGN NUKTA
	{runeRange{0x11236, 0x11236}, incbExtend},  // Mn       KHOJKI SIGN NUKTA
	{runeRange{0x1133B, 0x1133C}, incbExtend},  // Mn   [2] COMBINING BINDU BELOW..GRANTHA SIGN NUKTA
	{runeRange{0x11370, 0x11374}, incbExtend},  // Mn   [5] COMBINING GRANTHA LETTER A..COMBINING GRANTHA LETTER PA
	{runeRange{0x1145E, 0x1145E}, incbExtend},  // Mn       NEWA SANDHI MARK
	{runeRange{0x115C0, 0x115C0}, incbExtend},  // Mn       SIDDHAM SIGN NUKTA
	{runeRange{0x1172B, 0x1172B}, incbExtend},  // Mn       AHOM SIGN KILLER
	{runeRange{0x1193E, 0x1193E}, incbExtend},  // Mn       DIVES AKURU VIRAMA
	{runeRange{0x11A34, 0x11A34}, incbExtend},  // Mn       ZANABAZAR SQUARE SIGN VIRAMA
	{runeRange{0x11A99, 0x11A99}, incbExtend},  // Mn       SOYOMBO SUBJOINER
	{runeRange{0x11D44, 0x11D45}, incbExtend},  // Mn   [2] MASARAM GONDI SIGN HALANTA..MASARAM GONDI VIRAMA
	{runeRange{0x11F42, 0x11F42}, incbExtend},  // Mn       KAWI CONJOINER
	{runeRange{0x16B30, 0x16B36}, incbExtend},  // Mn   [7] PAHAWH HMONG MARK CIM TUB..PAHAWH HMONG MARK CIM TAUM
	{runeRange{0x1D165, 0x1D165}, incbExtend},  // Mc       MUSICAL SYMBOL COMBINING STEM
	{runeRange{0x1D16E, 0x1D172}, incbExtend},  // Mc   [5] MUSICAL SYMBOL COMBINING FLAG-1..MUSICAL SYMBOL COMBINING FLAG-5
	{runeRange{0x1D185, 0x1D18B}, incbExtend},  // Mn   [7] MUSICAL SYMBOL COMBINING DOIT..MUSICAL SYMBOL COMBINING TRIPLE TONGUE
	{runeRange{0x1D242, 0x1D244}, incbExtend},  // Mn   [3] COMBINING GREEK MUSICAL TRISEME..COMBINING GREEK MUSICAL PENTASEME
	{runeRange{0x1E008, 0x1E018}, incbExtend},  // Mn  [17] COMBINING GLAGOLITIC LETTER ZEMLJA..COMBINING GLAGOLITIC LETTER HERU
	{runeRange{0x1E023, 0x1E024}, incbExtend},  // Mn   [2] COMBINING GLAGOLITIC LETTER YU..COMBINING GLAGOLITIC LETTER SMALL YUS
	{runeRange{0x1E08F, 0x1E08F}, incbExtend},  // Mn       COMBINING CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
	{runeRange{0x1E2AE, 0x1E2AE}, incbExtend},  // Mn       TOTO SIGN RISING TONE
	{runeRange{0x1E4EC, 0x1E4EF}, incbExtend},  // Mn   [4] NAG MUNDARI SIGN MUHOR..NAG MUNDARI SIGN SUTUH
	{runeRange{0x1E944, 0x1E94A}, incbExtend},  // Mn   [7] ADLAM ALIF LENGTHENER..ADLAM NUKTA
	{runeRange{0x0300, 0x034E}, incbExtend},    // Mn  [79] COMBINING GRAVE ACCENT..COMBINING UPWARDS ARROW BELOW
	{runeRange{0x0483, 0x0487}, incbExtend},    // Mn   [5] COMBINING CYRILLIC TITLO..COMBINING CYRILLIC POKRYTIE
	{runeRange{0x05BF, 0x05BF}, incbExtend},    // Mn       HEBREW POINT RAFE
	{runeRange{0x05C4, 0x05C5}, incbExtend},    // Mn   [2] HEBREW MARK UPPER DOT..HEBREW MARK LOWER DOT
	{runeRange{0x0610, 0x061A}, incbExtend},    // Mn  [11] ARABIC SIGN SALLALLAHOU ALAYHE WASSALLAM..ARABIC SMALL KASRA
	{runeRange{0x0670, 0x0670}, incbExtend},    // Mn       ARABIC LETTER SUPERSCRIPT ALEF
	{runeRange{0x06DF, 0x06E4}, incbExtend},    // Mn   [6] ARABIC SMALL HIGH ROUNDED ZERO..ARABIC SMALL HIGH MADDA
	{runeRange{0x06EA, 0x06ED}, incbExtend},    // Mn   [4] ARABIC EMPTY CENTRE LOW STOP..ARABIC SMALL LOW MEEM
	{runeRange{0x0730, 0x074A}, incbExtend},    // Mn  [27] SYRIAC PTHAHA ABOVE..SYRIAC BARREKH
	{runeRange{0x07FD, 0x07FD}, incbExtend},    // Mn       NKO DANTAYALAN
	{runeRange{0x081B, 0x0823}, incbExtend},    // Mn   [9] SAMARITAN MARK EPENTHETIC YUT..SAMARITAN VOWEL SIGN A
	{runeRange{0x0829, 0x082D}, incbExtend},    // Mn   [5] SAMARITAN VOWEL SIGN LONG I..SAMARITAN MARK NEQUDAA
	{runeRange{0x0898, 0x089F}, incbExtend},    // Mn   [8] ARABIC SMALL HIGH WORD AL-JUZ..ARABIC HALF MADDA OVER MADDA
	{runeRange{0x08E3, 0x08FF}, incbExtend},    // Mn  [29] ARABIC TURNED DAMMA BELOW..ARABIC MARK SIDEWAYS NOON GHUNNA
	{runeRange{0x093C, 0x093C}, incbExtend},    // Mn       DEVANAGARI SIGN NUKTA
	{runeRange{0x0951, 0x0954}, incbExtend},    // Mn   [4] DEVANAGARI STRESS SIGN UDATTA..DEVANAGARI ACUTE ACCENT
	{runeRange{0x0978, 0x097F}, incbConsonant}, // Lo   [8] DEVANAGARI LETTER MARWARI DDA..DEVANAGARI LETTER BBA
	{runeRange{0x09AA, 0x09B0}, incbConsonant}, // Lo   [7] BENGALI LETTER PA..BENGALI LETTER RA
	{runeRange{0x09B6, 0x09B9}, incbConsonant}, // Lo   [4] BENGALI LETTER SHA..BENGALI LETTER HA
	{runeRange{0x09CD, 0x09CD}, incbLinker},    // Mn       BENGALI SIGN VIRAMA
	{runeRange{0x09DF, 0x09DF}, incbConsonant}, // Lo       BENGALI LETTER YYA
	{runeRange{0x09FE, 0x09FE}, incbExtend},    // Mn       BENGALI SANDHI MARK
	{runeRange{0x0A95, 0x0AA8}, incbConsonant}, // Lo  [20] GUJARATI LETTER KA..GUJARATI LETTER NA
	{runeRange{0x0AB2, 0x0AB3}, incbConsonant}, // Lo   [2] GUJARATI LETTER LA..GUJARATI LETTER LLA
	{runeRange{0x0ABC, 0x0ABC}, incbExtend},    // Mn       GUJARATI SIGN NUKTA
	{runeRange{0x0AF9, 0x0AF9}, incbConsonant}, // Lo       GUJARATI LETTER ZHA
	{runeRange{0x0B2A, 0x0B30}, incbConsonant}, // Lo   [7] ORIYA LETTER PA..ORIYA LETTER RA
	{runeRange{0x0B35, 0x0B39}, incbConsonant}, // Lo   [5] ORIYA LETTER VA..ORIYA LETTER HA
	{runeRange{0x0B4D, 0x0B4D}, incbLinker},    // Mn       ORIYA SIGN VIRAMA
	{runeRange{0x0B5F, 0x0B5F}, incbConsonant}, // Lo       ORIYA LETTER YYA
	{runeRange{0x0C15, 0x0C28}, incbConsonant}, // Lo  [20] TELUGU LETTER KA..TELUGU LETTER NA
	{runeRange{0x0C3C, 0x0C3C}, incbExtend},    // Mn       TELUGU SIGN NUKTA
	{runeRange{0x0C55, 0x0C56}, incbExtend},    // Mn   [2] TELUGU LENGTH MARK..TELUGU AI LENGTH MARK
	{runeRange{0x0CBC, 0x0CBC}, incbExtend},    // Mn       KANNADA SIGN NUKTA
	{runeRange{0x0D3B, 0x0D3C}, incbExtend},    // Mn   [2] MALAYALAM SIGN VERTICAL BAR VIRAMA..MALAYALAM SIGN CIRCULAR VIRAMA
	{runeRange{0x0E38, 0x0E3A}, incbExtend},    // Mn   [3] THAI CHARACTER SARA U..THAI CHARACTER PHINTHU
	{runeRange{0x0EB8, 0x0EBA}, incbExtend},    // Mn   [3] LAO VOWEL SIGN U..LAO SIGN PALI VIRAMA
	{runeRange{0x0F18, 0x0F19}, incbExtend},    // Mn   [2] TIBETAN ASTROLOGICAL SIGN -KHYUD PA..TIBETAN ASTROLOGICAL SIGN SDONG TSHUGS
	{runeRange{0x0F37, 0x0F37}, incbExtend},    // Mn       TIBETAN MARK NGAS BZUNG SGOR RTAGS
	{runeRange{0x0F71, 0x0F72}, incbExtend},    // Mn   [2] TIBETAN VOWEL SIGN AA..TIBETAN VOWEL SIGN I
	{runeRange{0x0F7A, 0x0F7D}, incbExtend},    // Mn   [4] TIBETAN VOWEL SIGN E..TIBETAN VOWEL SIGN OO
	{runeRange{0x0F82, 0x0F84}, incbExtend},    // Mn   [3] TIBETAN SIGN NYI ZLA NAA DA..TIBETAN MARK HALANTA
	{runeRange{0x0FC6, 0x0FC6}, incbExtend},    // Mn       TIBETAN SYMBOL PADMA GDAN
	{runeRange{0x1039, 0x103A}, incbExtend},    // Mn   [2] MYANMAR SIGN VIRAMA..MYANMAR SIGN ASAT
	{runeRange{0x135D, 0x135F}, incbExtend},    // Mn   [3] ETHIOPIC COMBINING GEMINATION AND VOWEL LENGTH MARK..ETHIOPIC COMBINING GEMINATION MARK
	{runeRange{0x17D2, 0x17D2}, incbExtend},    // Mn       KHMER SIGN COENG
	{runeRange{0x18A9, 0x18A9}, incbExtend},    // Mn       MONGOLIAN LETTER ALI GALI DAGALGA
	{runeRange{0x1A17, 0x1A18}, incbExtend},    // Mn   [2] BUGINESE VOWEL SIGN I..BUGINESE VOWEL SIGN U
	{runeRange{0x1A75, 0x1A7C}, incbExtend},    // Mn   [8] TAI THAM SIGN TONE-1..TAI THAM SIGN KHUEN-LUE KARAN
	{runeRange{0x1AB0, 0x1ABD}, incbExtend},    // Mn  [14] COMBINING DOUBLED CIRCUMFLEX ACCENT..COMBINING PARENTHESES BELOW
	{runeRange{0x1B34, 0x1B34}, incbExtend},    // Mn       BALINESE SIGN REREKAN
	{runeRange{0x1BAB, 0x1BAB}, incbExtend},    // Mn       SUNDANESE SIGN VIRAMA
	{runeRange{0x1C37, 0x1C37}, incbExtend},    // Mn       LEPCHA SIGN NUKTA
	{runeRange{0x1CD4, 0x1CE0}, incbExtend},    // Mn  [13] VEDIC SIGN YAJURVEDIC MIDLINE SVARITA..VEDIC TONE RIGVEDIC KASHMIRI INDEPENDENT SVARITA
	{runeRange{0x1CED, 0x1CED}, incbExtend},    // Mn       VEDIC SIGN TIRYAK
	{runeRange{0x1CF8, 0x1CF9}, incbExtend},    // Mn   [2] VEDIC TONE RING ABOVE..VEDIC TONE DOUBLE RING ABOVE
	{runeRange{0x200D, 0x200D}, incbExtend},    // Cf       ZERO WIDTH JOINER
	{runeRange{0x20E1, 0x20E1}, incbExtend},    // Mn       COMBINING LEFT RIGHT ARROW ABOVE
	{runeRange{0x2CEF, 0x2CF1}, incbExtend},    // Mn   [3] COPTIC COMBINING NI ABOVE..COPTIC COMBINING SPIRITUS LENIS
	{runeRange{0x2DE0, 0x2DFF}, incbExtend},    // Mn  [32] COMBINING CYRILLIC LETTER BE..COMBINING CYRILLIC LETTER IOTIFIED BIG YUS
	{runeRange{0x302E, 0x302F}, incbExtend},    // Mc   [2] HANGUL SINGLE DOT TONE MARK..HANGUL DOUBLE DOT TONE MARK
	{runeRange{0xA66F, 0xA66F}, incbExtend},    // Mn       COMBINING CYRILLIC VZMET
	{runeRange{0xA69E, 0xA69F}, incbExtend},    // Mn   [2] COMBINING CYRILLIC LETTER EF..COMBINING CYRILLIC LETTER IOTIFIED E
	{runeRange{0xA82C, 0xA82C}, incbExtend},    // Mn       SYLOTI NAGRI SIGN ALTERNATE HASANTA
	{runeRange{0xA92B, 0xA92D}, incbExtend},    // Mn   [3] KAYAH LI TONE PLOPHU..KAYAH LI TONE CALYA PLOPHU
	{runeRange{0xAAB0, 0xAAB0}, incbExtend},    // Mn       TAI VIET MAI KANG
	{runeRange{0xAAB7, 0xAAB8}, incbExtend},    // Mn   [2] TAI VIET MAI KHIT..TAI VIET VOWEL IA
	{runeRange{0xAAC1, 0xAAC1}, incbExtend},    // Mn       TAI VIET TONE MAI THO
	{runeRange{0xABED, 0xABED}, incbExtend},    // Mn       MEETEI MAYEK APUN IYEK
	{runeRange{0xFE20, 0xFE2F}, incbExtend},    // Mn  [16] COMBINING LIGATURE LEFT HALF..COMBINING CYRILLIC TITLO RIGHT HALF
	{runeRange{0x102E0, 0x102E0}, incbExtend},  // Mn       COPTIC EPACT THOUSANDS MARK
	{runeRange{0x10A0D, 0x10A0D}, incbExtend},  // Mn       KHAROSHTHI SIGN DOUBLE RING BELOW
	{runeRange{0x10A38, 0x10A3A}, incbExtend},  // Mn   [3] KHAROSHTHI SIGN BAR ABOVE..KHAROSHTHI SIGN DOT BELOW
	{runeRange{0x10AE5, 0x10AE6}, incbExtend},  // Mn   [2] MANICHAEAN ABBREVIATION MARK ABOVE..MANICHAEAN ABBREVIATION MARK BELOW
	{runeRange{0x10EAB, 0x10EAC}, incbExtend},  // Mn   [2] YEZIDI COMBINING HAMZA MARK..YEZIDI COMBINING MADDA MARK
}
