package uniseg

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"testing"
)

var generateTries = flag.Bool("generate-tries", false, "generate tries.go from the property dictionaries")

// TestGenerateTries generates tries.go from the property dictionaries. Run it
// with "go generate" after updating the dictionaries.
func TestGenerateTries(t *testing.T) {
	if !*generateTries {
		t.Skip("run with -generate-tries to generate tries.go")
	}

	var buf strings.Builder
	fmt.Fprintln(&buf, "// Code generated by trie_gen_test.go; DO NOT EDIT.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "package uniseg")
	writeTrie(t, &buf, "graphemeTrie", "graphemeProperties", "graphemeCodePoints and incb", lookupGraphemeProperties)
	writeTrie(t, &buf, "wordBreakTrie", "wbProperty", "workBreakCodePoints", workBreakCodePoints.search)
	writeTrie(t, &buf, "sentenceBreakTrie", "sbProperty", "sentenceBreakCodePoints", sentenceBreakCodePoints.search)
	writeTrie(t, &buf, "lineBreakTrie", "propertyGeneralCategory", "lineBreakCodePoints", lineBreakCodePoints.search)
	writeTrie(t, &buf, "eastAsianWidthTrie", "eawProperty", "eastAsianWidth", eastAsianWidth.search)
	writeTrie(t, &buf, "emojiTrie", "emojiProperty", "emoji", emoji.search)
	writeTrie(t, &buf, "emojiPresentationTrie", "emojiProperty", "emojiPresentation", emojiPresentation.search)

	src, err := format.Source([]byte(buf.String()))
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile("tries.go", src, 0o644); err != nil {
		t.Fatal(err)
	}
}

// writeTrie writes the Go source of the trie mapping code points to the values
// returned by lookup.
func writeTrie[T comparable](t *testing.T, buf *strings.Builder, name, typeName, source string, lookup func(rune) T) {
	t.Helper()

	// Map each code point to an index into the values. The zero value, which
	// is used for code points without a property, has index 0.
	var zero T
	values := []T{zero}
	valueIndex := map[T]uint8{zero: 0}
	indexes := make([]uint8, maxRune+1)
	for r := range rune(maxRune + 1) {
		v := lookup(r)
		idx, ok := valueIndex[v]
		if !ok {
			if len(values) > 0xff {
				t.Fatalf("%s: too many distinct values", name)
			}
			idx = uint8(len(values))
			valueIndex[v] = idx
			values = append(values, v)
		}
		indexes[r] = idx
	}

	// Build stage 3 by sharing identical blocks.
	const stage3Size = 1 << trieStage3Bits
	var stage3 []uint8
	stage3Blocks := map[[stage3Size]uint8]int{}
	var stage3IDs []int
	for i := 0; i < len(indexes); i += stage3Size {
		block := [stage3Size]uint8(indexes[i : i+stage3Size])
		id, ok := stage3Blocks[block]
		if !ok {
			id = len(stage3Blocks)
			stage3Blocks[block] = id
			stage3 = append(stage3, block[:]...)
		}
		stage3IDs = append(stage3IDs, id)
	}

	// Build stage 2 and stage 1 the same way.
	const stage2Size = 1 << trieStage2Bits
	var stage1, stage2 []uint16
	stage2Blocks := map[[stage2Size]uint16]int{}
	for i := 0; i < len(stage3IDs); i += stage2Size {
		var block [stage2Size]uint16
		for j := range block {
			id := stage3IDs[i+j]
			if id > 0xffff {
				t.Fatalf("%s: too many stage 3 blocks", name)
			}
			block[j] = uint16(id)
		}
		id, ok := stage2Blocks[block]
		if !ok {
			id = len(stage2Blocks)
			stage2Blocks[block] = id
			stage2 = append(stage2, block[:]...)
		}
		stage1 = append(stage1, uint16(id))
	}

	fmt.Fprintln(buf)
	fmt.Fprintf(buf, "// %s is the [trie] version of %s.\n", name, source)
	fmt.Fprintf(buf, "var %s = &trie[%s]{\n", name, typeName)
	fmt.Fprintf(buf, "stage1: []uint16{%s},\n", joinInts(stage1))
	fmt.Fprintf(buf, "stage2: []uint16{%s},\n", joinInts(stage2))
	fmt.Fprintf(buf, "stage3: []uint8{%s},\n", joinInts(stage3))
	fmt.Fprintf(buf, "values: []%s{", typeName)
	for _, v := range values {
		fmt.Fprintf(buf, "%s, ", strings.TrimPrefix(strings.ReplaceAll(fmt.Sprintf("%#v", v), "uniseg.", ""), typeName))
	}
	fmt.Fprintln(buf, "},")
	fmt.Fprintln(buf, "}")
}

// joinInts formats the integers as a comma separated list, 32 per line.
func joinInts[T uint8 | uint16](a []T) string {
	var sb strings.Builder
	for i, v := range a {
		if i%32 == 0 {
			sb.WriteString("\n")
		}
		fmt.Fprintf(&sb, "%d,", v)
	}
	sb.WriteString("\n")
	return sb.String()
}

// lookupGraphemeProperties returns the grapheme properties of r from the
// dictionaries.
func lookupGraphemeProperties(r rune) graphemeProperties {
	return graphemeProperties{
		property: graphemeCodePoints.search(r),
		incb:     incb.search(r),
	}
}
